version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2019
clone_depth: 5
init:
- ps: ''
install:
- ps: Install-Product node 14
- cmd: >-
    cd GDevelop.js

    git clone https://github.com/juj/emsdk.git

    cd emsdk

    emsdk install 1.39.6

    emsdk activate 1.39.6

    emsdk_env.bat

    cd ..

    npm install

    npm run build

    cd ..

    cd newIDE\app

    npm install

    cd ..\electron-app

    npm install

    cd ..\..

# Build the app on Windows.
build_script:
- cmd: >-
    cd newIDE\electron-app

    node --max-old-space-size=3072 scripts/build.js --win appx --publish=never

    node scripts/build.js --skip-app-build --win nsis --publish=never

    cd ..\..

# Run a few tests to ensure they work on Windows.
test_script:
- cmd: >-
    cd GDevelop.js

    npm test

    cd ..

    cd newIDE\app

    npm test

    cd ..\..

on_finish:
- ps: ''

artifacts:
  - path: newIDE\electron-app\dist
# TODO: Deploy on S3
